### ISSUE TITLE
Problema Función CrearGasto

### ISSUE THREAD

**Issue by CGC-2021** [CGC-2021/practica_dwec_gestor_presupuesto#1]
Hola @Pedroprieto El problema que te comenté está en la función CrearGasto (a partir de la línea 27 de  gestionPresupuesto.js).

**Comment by pedroprieto** [comment]
Buenas,

- Aquí almacenas en `this.fecha` un objeto de tipo `Date`, no el timestamp. Deberías convertir ese objeto a timestamp
  https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/93a8579ef87035a1059adede1fd3289f5e3fb066/js/gestionPresupuesto.js#L38
- Esto está bien, para inicializar:
  https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/93a8579ef87035a1059adede1fd3289f5e3fb066/js/gestionPresupuesto.js#L47
- Esto te sobra (hasta la línea 29):
  https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/93a8579ef87035a1059adede1fd3289f5e3fb066/js/gestionPresupuesto.js#L49
- Lo que te faltaría sería asignar el parámetro `etiquetas` a `this.etiquetas`, comprobando antes si `etiquetas` está definido. Algo así:
```js
if (etiquetas) {
  this.etiquetas = etiquetas;
}
```

Lo único, no compruebas duplicados. Una solución mejor sería añadir las etiquetas aprovechando el método `this.anyadirEtiquetas` que todavía tienes que crear.

Un saludo!

**Comment by CGC-2021** [comment]
Gracias Pedro, ya he pasado el segundo punto del test. Voy a ver si puedo seguir avanzando y me voy poniendo al día.
Estos ejercicios son "sencillos" pero me cuesta mucho pensarlos a nivel lógico. Tendré en cuenta lo del método "anyadirEtiquetas".
Mil gracias por la ayuda!

**Comment by pedroprieto** [comment]
:+1:
