### ISSUE TITLE
Consulta tests Intro JS II 

### ISSUE THREAD

**Issue by CGC-2021** [CGC-2021/practica_dwec_gestor_presupuesto#2]
Hola de nuevo @pedroprieto,

sigo teniendo problemas con los tests de JS II. En esta ocasión no consigo hacer funcionar **borrarGasto** y **calcularTotalGasto** (no entiendo de dónde sale el resultado que suma la función, la he usado aparte y sí funcionaba).

Gracias.

**Comment by pedroprieto** [comment]
Buenas,

En `borrarGasto` tienes aquí un segundo bucle que no es correcto:
https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/74d2a10516c37c81cdceb9cc77eac7853a05e0cb/js/gestionPresupuesto.js#L151

Recuerda que `idNueva` es un parámetro de la función, y que contendrá el `id` del gasto a borrar. Por tanto, no es un objeto ni un array y no tienes que utilizar ningún bucle.

Además, el resto de la lógica de esa función no es correcta tampoco. `splice` admite como parámetro la posición, no el elemento.

En cuanto a los fallos en el resto de los tests, el problema es que `borrarGasto` no te funciona y genera un error en el resultado que te provoca que `calcularTotalGastos` falle también. Lo siento, es un fallo mío en el diseño de los tests :sob: Intentaré solucionarlo. Verás que en cuanto te funcione `borrarGasto` te funcionan todos.

Un saludo y ánimo!

**Comment by pedroprieto** [comment]
Por si no quedaba claro, `calcularTotalGastos` está bien.

**Comment by CGC-2021** [comment]
Repasando la teoría he conseguido arreglarlo, mil gracias de nuevo, Pedro.

Voy a intentar ser más rápida con los test pero si veo que no llego a entregarlos a tiempo te lo haré saber para borrar mi asistencia al examen.

Un saludo!

**Comment by pedroprieto** [comment]
Sin problema :+1: 

Puedes presentarte al examen sin tener todas las prácticas entregadas. Las que tengas pendientes pueden ser entregadas después.

Un saludo!!
