### ISSUE TITLE
Problema con filtrarGastos

### ISSUE THREAD

**Issue by CGC-2021** [CGC-2021/practica_dwec_gestor_presupuesto#3]
Hola @pedroprieto, 

tengo problemas con la práctica de JS III, concretamente con la función filtrarGastos (línea 198).

El test me dice que la opción "fechaDesde" no funciona correctamente y no sé por qué (he probado varias cosas porque creo que el error está en lo que estoy devolviendo con los if, pero cada vez me estoy complicando más y no encuentro solución).

He repasado varias veces la explicación de la tutoría del 26 de octubre pero no sé exactamente qué tengo mal.

Gracias y disculpa la demora con las prácticas.

**Comment by pedroprieto** [comment]
Buenas,

El problema está aquí:
https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/04dd09435eececb3e35ca3eda0a1eb8e234da245/js/gestionPresupuesto.js#L220

`opciones.fechaDesde` es una cadena de texto. Tienes que convertirla con `Date.parse` (como haces en el `if`) para comparar con `gasto.fecha`, que es un timestamp.

Un saludo!

**Comment by CGC-2021** [comment]
Hola de nuevo, @pedroprieto . Solucionado lo de las fechas, gracias.

Ahora tengo otro problema que igual es de comprensión del enunciado.

En la línea 263, no sé exactamente qué debe devolver etiquetasTiene. He puesto un return que debería devolver las etiquetas coincidentes (he probado el código aparte y funciona) pero creo que no es exactamente eso lo que se pide. No sé cómo devolverlo en el resultado general del filtrado.

Un saludo y disculpa que te plantee dudas de hace meses, estoy intentando recuperar las prácticas y voy más despacio de lo que me gustaría.

**Comment by pedroprieto** [comment]
Buenas,

No te preocupes, no hay problema.

`etiquetasTiene` es un array. Por tanto, no puedes pasarlo directamente como parámetro al `includes`, ya que esa función espera un elemento que pueda aparecer en el array:
https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/04dd09435eececb3e35ca3eda0a1eb8e234da245/js/gestionPresupuesto.js#L270

Debes iterar `etiquetasTiene` y comprobar cada elemento en el `includes`.

Un saludo!!

**Comment by CGC-2021** [comment]
Hola Pedro,

te lo he comentado en la Pull Request pero te envié el Issue desde otro ordenador (desde el que hice Push) y el trozo de código relativo a las etiquetas era diferente porque había puesto un par de iteraciones para comparar (y había quitado el includes).
Lo que me faltaba era por devolver el resultado si las etiquetas no coincidían.

**Comment by pedroprieto** [comment]
Correcto pues. Ya lo he visto. Buen trabajo!! :+1:
