### ISSUE TITLE
Problema sintaxis y test4 Interacción HTML

### ISSUE THREAD

**Issue by CGC-2021** [CGC-2021/practica_dwec_gestor_presupuesto#4]
Hola de nuevo @pedroprieto.

Al pasar el test número 4 me está saltando un error de sintaxis (Unexpected token "(" ) pero por más que miro no lo encuentro y no he podido comprobar ni los primeros puntos del test. 

Gracias!

**Comment by pedroprieto** [comment]
Buenas,

https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/1b31fdf8f2fcc71c0a7cf3c5c34f1319b51dc09b/js/generarDatosEstaticos.js#L1-L2

Las rutas no deben llevar paréntesis.

Un saludo!

**Comment by CGC-2021** [comment]
Vaya error... gracias Pedro!.

**Comment by pedroprieto** [comment]
De res :blush:
