### ISSUE TITLE
Problema con práctica 6 Formularios

### ISSUE THREAD

**Issue by CGC-2021** [CGC-2021/practica_dwec_gestor_presupuesto#5]
Hola @pedroprieto,

intentando pasar los test de la práctica de Formularios me salta un error que no acabo de entender y no sé si es cuestión de sintaxis o de estructura.

El error es:  AssertionError: Timed out retrying after 4000ms: Expected to find element: `#controlesprincipales form`, but never found it. 

Te adjunto captura (he subido el código actualizado también).

![Captura de pantalla 2022-02-15 135736](https://user-images.githubusercontent.com/79537403/154066683-44c8b8df-3606-4eca-82db-41f9be72239e.png)

¡Gracias!

**Comment by pedroprieto** [comment]
Buenas,

El problema está aquí:
https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/fd58f54d04fb08ac0f4fdec40abc7396f4aa6641/js/gestionPresupuestoWeb.js#L4

Esa función es un constructor de objetos de eventos, no una manejadora de ventos. Por tanto, debes crear el objeto con `new`:
https://es.javascript.info/introduction-browser-events#objetos-handlers-handleevent

Un saludo!!

**Comment by CGC-2021** [comment]
He vuelto a subir el código con la modificación pero ahora me salta otro error:

"Invalid time value"

![captura_error_invalidTime](https://user-images.githubusercontent.com/79537403/154254404-00c6d545-456b-4b6f-b700-67f45db01ae7.png)

gracias de nuevo, Pedro! Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Tienes un bug oculto:
https://github.com/CGC-2021/practica_dwec_gestor_presupuesto/blob/7bccc0848ff8f876287556b50867d5e8456d2daf/js/gestionPresupuesto.js#L138

Es `this.fecha`.

Me ha costado!! :sweat_smile: 

Un saludo!!

**Comment by CGC-2021** [comment]
Vaya, me había olvidado por completo ya de ese archivo! 

mil gracias, ya me pasa el test! :)


Un saludo!
